### ISSUE TITLE
Severely degraded crosshair performance

### ISSUE THREAD

**Issue by tannerlinsley** [observablehq/plot#1694] opened 2023-06-14 22:37 UTC
When adding a crosshair to one of our plots with ~4,000 datums/elements, mousemove/hover/tooltip/crosshair performance degrades to single-frame updates over the course of many seconds. I've attached a screenshot below of our performance profile that may lead to the cause:

<img width="981" alt="Screen Shot 2023-06-14 at 4 34 59 PM" src="https://github.com/observablehq/plot/assets/5580297/42a5c7ab-2341-438f-8aa5-0d3ab8d9ef89">

**Comment by mbostock** [comment] 2023-06-15 00:36
Is there a live reproduction you can share?

**Comment by mbostock** [comment] 2023-06-15 15:30
There are ~12,000 elements in this crosshair plot and I see no issues with performance:

https://observablehq.com/@observablehq/plot-crosshair

So, I expect something else is going on here. For example, perhaps you are using opacity (instead of fill-opacity and stroke-opacity), or mix-blend-mode, or something else that might cause render slowness.

Are you doing anything else “unusual” here? It does seem a little surprising to see getScreenCTM in the flamegraph, since that is normally a cheap operation. But perhaps you are doing something that is modifying styles during pointermove? In any case, I can’t debug the slowness without more context so I’m going to close this issue. If you can share more please do and I will reopen.

**Closed by mbostock** 2023-06-15 15:30 UTC
Labels: question

**Comment by tannerlinsley** [comment] 2023-06-16 16:08
Oooo opacity might be it. I’ll get a more reproducible example, even if it’s to confirm that.

Tanner Linsley
