### ISSUE TITLE
When a sort.limit is applied, marks that are filtered out can still affect scale domains

### ISSUE THREAD

**Issue by eagereyes** [observablehq/plot#1313] opened 2023-03-04 00:46 UTC
When using `barX()`, the axis starts at ~~0~~ 1 even though it should start at 300 [in this example](https://observablehq.com/d/7917d19d9da976e1).

Plot code:
```
Plot.plot({
  marks: [
    Plot.barX(olympians, Plot.groupY({x2: "count"}, {x1: 300, y: "nationality", sort: {y: "x", reverse: true, limit: 10}})),
    Plot.ruleX([300])
  ]
})
```

Only when the domain is set manually does the axis start at 300 as expected.

**Comment by mbostock** [comment] 2023-03-04 00:58
The problem is the sort.limit: even though this truncates the _y_-domain to only show the top N bars, the other bars are still considered when computing the _x_-domain. And since the smallest bar (as you might expect) has a count of _y_ = 1, the _x_-domain starts at one. This can be seen by removing the limit:

![untitled (18)](https://user-images.githubusercontent.com/230541/222863712-1471f00f-ad82-4a7f-a210-94382ff594f8.png)

```js
Plot.plot({
  marks: [
    Plot.barX(olympians, Plot.groupY({x2: "count"}, {x1: 300, y: "nationality", sort: {y: "x", reverse: true}})),
    Plot.ruleX([300])
  ]
})
```

To fix this, we’d need to keep track not just of the channels bound to each scale, but the mark indexes associated with those channels, and only consider values that are referenced by the (filtered) indexes.

**Comment by mbostock** [comment] 2023-03-04 01:12
I’m not sure we’re going to be able to solve this one (easily). In order to solve it, we’d have to allow imputed scale domains to be interdependent: if the imputed domain of _y_ filters out some data, that would truncate the imputed domain of _x_. But I’m not sure how we would know which scale domain depends on which other scales, and therefore the order in which to compute them. Just keep filtering repeatedly until nothing is dropped? Heh. 🤔

**Comment by Fil** [comment] 2023-03-06 16:02
This is a case where I'd prefer to have to explain what happens (and keep it simple), rather than try and change it with a more complex logic.

The same question applies in a simpler but similar case: when you use the _filter_ option. Adding a _filter_ does not remove the filtered values from the scales domains. I think that's OK, even if it means that there is often a bit of manual adjustment.

Closing as such, please reopen if you disagree or have a better plan.

**Closed by Fil** 2023-03-06 16:02 UTC
Labels: question
