### ISSUE TITLE
Rect mark does not display with defined domain and only one data point

### ISSUE THREAD

**Issue by zachbogart** [observablehq/plot#1357] opened 2023-03-17 21:36 UTC
Found that if I explicitly define the domain for a histogram with a rect mark and the dataset only has one data point, no bar is visible. Expected behavior is that the bar should show up within domain as a skinny bar. 

Here's a [notebook](https://observablehq.com/d/f649fb100e9d366e) demonstrating the issue.

<img width="1153" alt="Screen Shot 2023-03-17 at 2 34 48 PM" src="https://user-images.githubusercontent.com/31786233/226057620-a97c0051-4749-468c-8eee-ac98040021a7.png">

**Comment by mbostock** [comment] 2023-03-17 22:13
The problem is that the rect has zero width because the domain of the data is trivial (collapsed). You can see the rect by setting a negative inset:

![untitled (27)](https://user-images.githubusercontent.com/230541/226060992-845198db-a93b-47eb-88ca-1e18a4003057.png)

```js
Plot.plot({
  x: {
    domain: [6, 9],
    label: "Trade volume (log₁₀) →"
  },
  y: {
    grid: true
  },
  marks: [
    Plot.rectY(aapl.slice(0, range), Plot.binX({y: "count"}, {inset: -1, x: d => Math.log10(d.Volume)})),
    Plot.ruleY([0])
  ]
})
```

One way to fix this is to set a fixed interval for the bin transform, such as 0.1. This means that the bin width will be 0.1 instead of 0, even if there’s only one value being binned.

![untitled (28)](https://user-images.githubusercontent.com/230541/226061123-2bd37533-2901-4092-9d6b-54a5d145affd.png)

```js
Plot.plot({
  x: {
    domain: [6, 9],
    label: "Trade volume (log₁₀) →"
  },
  y: {
    grid: true
  },
  marks: [
    Plot.rectY(aapl.slice(0, range), Plot.binX({y: "count"}, {x: d => Math.log10(d.Volume), interval: 0.1})),
    Plot.ruleY([0])
  ]
})
```

A different way of fixing this is to specify the domain explicitly to the bin transform (in addition to or instead of the scale), so that it knows the range that the bins should cover. However, you’ll also currently need to specify a count of thresholds yourself, since d3.thresholdScott has a bug (noticed thanks to you!) where it returns NaN if the domain is trivial.

![untitled (29)](https://user-images.githubusercontent.com/230541/226061760-5c67d7b2-2131-4bf5-8497-5a13b6e37809.png)

```js
Plot.plot({
  x: {
    domain: [6, 9],
    label: "Trade volume (log₁₀) →"
  },
  y: {
    grid: true
  },
  marks: [
    Plot.rectY(aapl.slice(0, range), Plot.binX({y: "count"}, {x: d => Math.log10(d.Volume), domain: [6, 9], thresholds: 10})),
    Plot.ruleY([0])
  ]
})
```

It might be nice if the bin domain could default to the scale domain, but that’s not usually possible since binning is a transform which happens prior to scale construction. And it’s more common that the scale domain is imputed from the binned domain than vice versa.

**Closed by mbostock** 2023-03-17 22:13 UTC

**Comment by zachbogart** [comment] 2023-03-17 22:35
Thanks, appreciate the explanation and glad to help!

**Comment by mbostock** [comment] 2023-03-24 16:27
One more thing: you can omit the redundant **domain** option on the _x_ scale if you set the **filter** option to null on the bin transform, such that the bin transform includes empty bins to span the entire domain. Like so:

![untitled (31)](https://user-images.githubusercontent.com/230541/227584858-a1273ad9-4468-4170-a6b7-470d757c64cc.png)

```js
Plot.plot({
  x: {label: "Trade volume (log₁₀) →"},
  y: {grid: true},
  marks: [
    Plot.rectY(aapl, Plot.binX({y: "count", filter: null}, {x: d => Math.log10(d.Volume), domain: [6, 9]})),
    Plot.ruleY([0])
  ]
})
```
