### ISSUE TITLE
Adjust dx and dy position of Plot.image marks

### ISSUE THREAD

**Issue by mkfreeman** [observablehq/plot#663] opened 2022-01-11 18:29 UTC
In the same way that `Plot.text` supports `dx` and `dy` attributes to adjust the positioning of the text, it would be great to afford similar behavior for `Plot.image` marks. 

Looking at the [svg image documnetation](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image), it appears as if the only native option is to use a `transform` property. 

We could expose `dx` and `dy` options to in the Plot API (to match `Plot.text`), and use them to assign the `translate` property where:

```js
const transformX = dx || 0;
const transformY = dy || 0;
const transform = translate(dx, dy)
```

**Comment by Fil** [comment] 2022-01-11 18:42
duplicate of https://github.com/observablehq/plot/issues/653, closed by #629

**Closed by Fil** 2022-01-11 18:42 UTC
Labels: enhancement
