### ISSUE TITLE
Fixed data aspect ratio?

### ISSUE THREAD

**Issue by Fil** [observablehq/plot#836] opened 2022-04-05 06:59 UTC
Sometimes you want x and y to be comparable, maybe because they both represent similar quantities in the same physical dimension. Plot currently has no way [1] to ask for a fixed "data aspect ratio", since x and y will both fill the available space.

Note that the expected aspect ratio is not necessarily 1:1, for example if your data are longitude and latitude, the correct setting might be to set a dataAspectRatio = [1, cos(median latitude)].

For this, MATLAB offers [daspect](https://fr.mathworks.com/help/matlab/creating_plots/manipulating-axes-aspect-ratio.html); ggplot2 has [coord_fixed](https://ggplot2.tidyverse.org/reference/coord_fixed.html); MASS has [geometrically equal scales](https://rdrr.io/cran/MASS/man/eqscplot.html):
* daspect is expressed as an array of ratios for x, y (and z) : [1 1] or [1 1 1].
* coord_fixed is expressed as a single number y/x

[1] of course you can specify ranges explicitly, but then the axes won't adapt to the chart's dimensions.

**Comment by mbostock** [comment] 2022-05-29 04:32
Duplicate of #445.

**Closed by mbostock** 2022-05-29 04:32 UTC
Labels: enhancement
