### ISSUE TITLE
Plot.raster mixBlendMode firefox

### ISSUE THREAD

**Issue by abenrob** [observablehq/plot#1815] opened 2023-08-17 10:43 UTC
Hey folks - I was checking out Jo Wood's _amazing_ {Topographic Mapping](https://observablehq.com/@jwolondon/topographic-mapping) notebook. On Chrome, the [mixBlendMode](https://observablehq.com/@jwolondon/topographic-mapping#cell-249) looks great
![untitled (1)](https://github.com/observablehq/plot/assets/3422185/b62fb52a-87ed-4335-a665-0945811851c2)

On Firefox, however, it does not.

![untitled(4)](https://github.com/observablehq/plot/assets/3422185/8642fede-837d-416f-b58f-3aa7fe7f561f)

**Comment by abenrob** [comment] 2023-08-17 10:50
FF 116.0.2 (64-bit)
macOS Monterey v12.5

**Comment by abenrob** [comment] 2023-08-17 10:59
Looks like the `mixBlendMode` is set on the `<image>`. If I instead add it to the containing `<g>` if works in Firefox (as well as Chrome).

![Screen Shot 2023-08-17 at 12 56 19](https://github.com/observablehq/plot/assets/3422185/d1b9dca1-0fd1-4964-af42-f528783a0654)

**Comment by mbostock** [comment] 2023-08-17 14:06
We don’t typically include workarounds for browser bugs in Plot. Moving the mixBlendMode up to the pattern G changes the semantics if there are multiple images. Though, maybe in this case we can make an exception? In any case probably best to file a bug with Firefox first.

**Comment by Fil** [comment] 2023-08-17 19:46
I can't reproduce (it works in Firefox for me).

tested on MacOS Ventura 13.4.1 (22F82) with FF 115.0.3 (64 bits) and FF 116.0.2 (64 bits) and 116.0.3 (64 bits) [For some reason Firefox upgraded twice while I was checking!]

**Comment by dunstan** [comment] 2023-08-17 23:18
Same experience for me as Fil. Works fine logged out in FF 107 and also when I updated to FF 116.0.3 (OS Venture 13.4.1).

**Comment by mbostock** [comment] 2023-08-17 23:37
Closing as this is either a browser bug, or not reproducible, and hence we do not plan on taking any action. But please feel free to continue discussing.

**Closed by mbostock** 2023-08-17 23:37 UTC

**Comment by abenrob** [comment] 2023-08-18 15:13
> I can't reproduce (it works in Firefox for me).
> 
> tested on MacOS Ventura 13.4.1 (22F82) with FF 115.0.3 (64 bits) and FF 116.0.2 (64 bits) and 116.0.3 (64 bits) [For some reason Firefox upgraded twice while I was checking!]

Weird. I just updated to Ventura 13.5.1, and the _issue persists_! I guess an odd FF+OSX edge case issue. I'll try to open a ticket with Mozilla. Thanks!

**Comment by abenrob** [comment] 2023-08-22 09:07
Just for info and completeness - this issue only occurs in firefox, _with my external monitor_ (!) 
- Chrome + monitor = no issue
- Chrome + laptop = no issue
- Firefox + monitor = issue
- Chrome + laptop = no issue

Thanks for having looked into it nevertheless!
