### ISSUE TITLE
Shape/Symbol channel

### ISSUE THREAD

**Issue by ericemc3** [observablehq/plot#389] opened 2021-05-12 14:47 UTC
Shape is one of the important visual properties according to Jacques Bertin, with quite good separation properties. 
 
![image](https://user-images.githubusercontent.com/17407796/117990191-33e5b080-b33d-11eb-8c03-895e573618ac.png)

A new shape (or symbol) channel would be very welcome.

Note: Vega-lite and ggplot2 can handle this type of representation.

PS: Plot is a great library, very intellectually stimulating, and the 21 beautifully written articles in the https://observablehq.com/collection/@observablehq/plot collection should be read by all data scientists!

**Comment by mbostock** [comment] 2021-05-12 15:19
Duplicate of #41.

**Closed by mbostock** 2021-05-12 15:19 UTC
