### ISSUE TITLE
Donut or Pie chart

### ISSUE THREAD

**Issue by kzmKZuzmo** [observablehq/plot#2166] opened 2024-09-10 10:17 UTC
Hey is there a way to create plot with donut or pie chart ?

**Comment by Fil** [comment] 2024-09-10 10:24
duplicate of #80 (see also #85)

**Closed by Fil** 2024-09-10 10:24 UTC
Labels: enhancement

**Comment by kzmKZuzmo** [comment] 2024-09-10 10:44
hey @Fil  so plot gonna be have or not the pie or donut ? I can't understand from (of https://github.com/observablehq/plot/issues/80 (see also https://github.com/observablehq/plot/pull/85)) that whether it will contain or not

**Comment by Fil** [comment] 2024-09-10 10:59
It means we're working on it, but it's not a high priority; #85 shows one way to do it.
