### ISSUE TITLE
provide d3.threshold as a valid scale

### ISSUE THREAD

**Issue by EE2dev** [observablehq/plot#374] opened 2021-05-10 22:28 UTC
One thing where I thought Plot and observable complements each other nicely is: when I map a quantitative column (e.g. age) to a color scale of let's say 3 colors (e.g. domain: [<30, 30-50, 50+], range:["red","blue","green"]. Then I would like to add two range inputs so the user can interactively adjust the two cutoff point (30 and 50) . I understand for a diverging color scale and one cutoff, the pivot is the way to go. But for the general case, I thought of using d3.threshold, but this is not a valid color scale type. I didn't want to transform (bin) the values interactively since it seems inefficient.

**Comment by mbostock** [comment] 2021-05-11 02:12
Duplicate of #372. 👍

**Closed by mbostock** 2021-05-11 02:12 UTC
