### ISSUE TITLE
Accepting functions for all mark options

### ISSUE THREAD

**Issue by EE2dev** [observablehq/plot#413] opened 2021-05-21 10:06 UTC
The mark options are divided into channels and constants, the latter accepting just string literals or a number.
For the latter, I think there are many cases where it would come handy, if one could provide a callback function to determine the string/ number in order to decide based on the data. (Not just for the channels)

E.g. 
`Plot.text(data, { x: "customers", y: "state", text: "customers", dx: (d) => (condition) ? -24 : -8, })`
or 
`Plot.text(data, { x: "customers", y: "state", text: "customers", stroke: : (d) => (condition) ? "white" : "black", })`

**Comment by mbostock** [comment] 2021-05-21 13:44
Duplicate of #175

**Closed by mbostock** 2021-05-21 13:44 UTC
