### ISSUE TITLE
Title, subtitle, source, copyright

### ISSUE THREAD

**Issue by ericemc3** [observablehq/plot#382] opened 2021-05-12 14:39 UTC
According to the usual rules of legibility, a chart should include an informative title, coming first (above the chart), possibly a subtitle, obligatorily a source, at the bottom of the chart, more optionally a copyright (which can also be arranged vertically, e.g. bottom right).

![image](https://user-images.githubusercontent.com/17407796/117984426-211cad00-b338-11eb-94e4-7fbc703c3e6f.png)
 
ggplot2 and vega-lite allow you to specify these essential elements, it would be very nice if Plot could as well.

The SVG export of the Plot should allow you to get the whole graphic, with titles and sources.

As vega-lite proposes, specifying a title as an array allows it to be spread over several lines.

The height specified for the graphic should not take these elements into account, but only the central body of the graphic.

PS: Plot is a great library, very intellectually stimulating, and the 21 beautifully written articles in the https://observablehq.com/collection/@observablehq/plot collection should be read by all data scientists!

**Comment by mbostock** [comment] 2021-05-12 15:21
Note that a caption option is already supported.

**Comment by Fil** [comment] 2021-05-12 15:50
Complements #92

**Comment by Fil** [comment] 2021-05-12 15:51
Eric please copy your comment over to #92 and close this issue?

**Comment by mbostock** [comment] 2021-05-12 16:03
Duplicate of #92. Please copy over your comment and continue discussion there.

**Closed by mbostock** 2021-05-12 16:03 UTC

**Comment by Fil** [comment] 2023-08-10 12:55
completed in https://github.com/observablehq/plot/pull/1761
