### ISSUE TITLE
Document piecewise/polylinear scales

### ISSUE THREAD

**Issue by mbostock** [observablehq/plot#1637] opened 2023-05-25 17:11 UTC
The documentation for continuous scales only covers two-element domains and ranges, but we support an arbitrary number of elements. This is most useful for color scales. We should document how this works.

Ref. https://github.com/observablehq/plot/pull/1633#issuecomment-1563159407

**Comment by Fil** [comment] 2023-06-25 09:35
Revise this in light of #1637

**Comment by Fil** [comment] 2024-09-09 15:18
duplicate of #2107 (or, the other way around), closed by #2112

**Closed** 2024-09-09 15:19 UTC
Labels: documentation
