### ISSUE TITLE
Axis on both ends of a dimension

### ISSUE THREAD

**Issue by yurivish** [observablehq/plot#571] opened 2021-10-01 15:59 UTC
For charts that are very tall or wide (e.g. table-like plots such as a faceted tick plot), it would be useful to be able show an axis on both ends of a dimension. 

This would make it easier to read specific values from the plot near the bottom or right of the chart, particularly when the top axis has been scrolled off-screen.

**Comment by mbostock** [comment] 2021-10-01 16:01
Agreed! Duplicate of #148.

**Closed by mbostock** 2021-10-01 16:01 UTC
